# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/bd/design_1/ip/design_1_axi_full_module_pope_0_0/design_1_axi_full_module_pope_0_0.xci
# IP: The module: 'design_1_axi_full_module_pope_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w72xd512/fifo_w72xd512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w288xd512/fifo_w288xd512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w144xd512/fifo_w144xd512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w40xd16/fifo_w40xd16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/bd/design_1/ip/design_1_axi_full_module_pope_0_0/design_1_axi_full_module_pope_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_full_module_pope_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/bd/design_1/ip/design_1_axi_full_module_pope_0_0/design_1_axi_full_module_pope_0_0.xci
# IP: The module: 'design_1_axi_full_module_pope_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w72xd512/fifo_w72xd512.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w288xd512/fifo_w288xd512.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w144xd512/fifo_w144xd512.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/ip/fifo_w40xd16/fifo_w40xd16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/bd/design_1/ip/design_1_axi_full_module_pope_0_0/design_1_axi_full_module_pope_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_full_module_pope_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
