# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/XC7Z010/0_axi_full_module/axi_full_module_popeye.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
