# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_w72xd512/fifo_w72xd512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] -quiet

# IP: ip/fifo_w288xd512/fifo_w288xd512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] -quiet

# IP: ip/fifo_w144xd512/fifo_w144xd512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] -quiet

# IP: ip/fifo_w40xd16/fifo_w40xd16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axi_full_module_pope_0_0/system_axi_full_module_pope_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_full_module_pope_0_0 || ORIG_REF_NAME==system_axi_full_module_pope_0_0} -quiet] -quiet

# IP: ip/fifo_w72xd512/fifo_w72xd512.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] -quiet

# IP: ip/fifo_w288xd512/fifo_w288xd512.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] -quiet

# IP: ip/fifo_w144xd512/fifo_w144xd512.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] -quiet

# IP: ip/fifo_w40xd16/fifo_w40xd16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dds_gen_crtl_0_0/system_dds_gen_crtl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_gen_crtl_0_0 || ORIG_REF_NAME==system_dds_gen_crtl_0_0} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_99M_0/system_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_99M_0 || ORIG_REF_NAME==system_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w72xd512/fifo_w72xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w72xd512 || ORIG_REF_NAME==fifo_w72xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w288xd512/fifo_w288xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w288xd512 || ORIG_REF_NAME==fifo_w288xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w144xd512/fifo_w144xd512_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w144xd512 || ORIG_REF_NAME==fifo_w144xd512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/fifo_w40xd16/fifo_w40xd16_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_w40xd16 || ORIG_REF_NAME==fifo_w40xd16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/bd/system/system_ooc.xdc
