# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tzh/Desktop/axi_full_module_control/1_axi_full_module_dds/axi_full_module_popeye.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
